config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  get '/about', to: 'about#index'
  get '/about/:team_member_id', to: 'about#show', as: 'team_member'

  resources :projects, only: [:show]
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @team_members = User.sorted_team
  end

  def show
    @team_member = User.friendly.find(params[:team_member_id])
    @prev_team_member = @team_member.prev
    @next_team_member = @team_member.next
  end
end

app/views/about/_hiring.html.erb
<section class="m-message">
  <div class="row">
    <div class="grid-sm-14 grid-lg-12 offset-lg-1">
      <p>We're hiring.</p>
      <%= link_to 'Apply', 'http://vizzuality.github.io/job-offers/', class: 'btn' %>
    </div>
  </div>
</section>

app/views/about/_pagination.html.erb
<section class="m-prev-next-team">
  <div class="row">
    <div class="grid-sm-14 grid-lg-12 offset-lg-1">
      <div class="m-prev-next-team-items">
        <% if @prev_team_member %>
          <div class="m-prev-team-item">
            <div>
              <%= link_to '', team_member_path(@prev_team_member), class: 'full-clickable' %>
              <p>Prev</p>
              <h2><%= @prev_team_member.name %></h2>
              <p class="position"><%= @prev_team_member.position %></p>
            </div>
          </div>
        <% end %>

        <% if @next_team_member %>
          <div class="m-next-team-item">
            <div>
              <%= link_to '', team_member_path(@next_team_member), class: 'full-clickable' %>
              <p>Next</p>
              <h2><%= @next_team_member.name %></h2>
              <p class="position"><%= @next_team_member.position %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/about/index.html.erb
<% title 'About us' %>
<% body_class 'is-about-page' %>

<% content_for :claim do %>
  <div class="row">
    <div class="grid-sm-14 grid-lg-12 offset-lg-1">
      <div class="m-claim">
        <article>
          <p>Great user experiences for stories that matter.</p>
          <p class="description">
            We are Vizzuality: a band of engineers, designers, <br>
            strategists and scientists dedicated to making your data matter
          </p>
          <%= link_to 'Our team', '#team', class: 'btn-secondary is-anchor' %>
          <%= link_to 'Contact', '#contact', class: 'btn is-anchor' %>
        </article>
      </div>
    </div>
  </div>
<% end %>

<section class="m-about">
  <div class="row">
    <div class="grid-sm-14 grid-lg-12 offset-lg-1">
      <ul class="m-team-gallery" id="team">
        <% @team_members.each do |m| %>
          <li style="background-image: url(<%= m.photo.url(:medium) %>)">
            <%= link_to team_member_path(m.slug) do %>
              <div class="veil"></div>
              <div class="m-team-gallery-content">
                <h3><%= m.name %></h3>
                <p><%= m.position%></p>
                <%= image_tag m.photo.url(:medium), class: 'is-hidden'%>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</section>

<%= render 'about/hiring' %>

<section class="m-map">
  <div id="mapInput">
    <div class="row">
      <div class="grid-sm-14 grid-lg-12 offset-lg-1"></div>
    </div>
  </div>

  <div id="map"></div>

  <div class="m-map-locations">
    <div class="row">
      <div class="grid-sm-14 grid-lg-6 offset-lg-1">
        <div id="madridOffice" class="m-map-location-item is-highlighted">
          <h3>Madrid</h3>
          <p>C/ Eloy Gonzalo, 27, 2 <br> 28010, Madrid <br> Spain</p>
        </div>
      </div>
      <div class="grid-sm-14 grid-lg-6">
        <div id="cambridgeOffice" class="m-map-location-item">
          <h3>Cambridge</h3>
          <p>Office D, Dales Brewery <br> Gwydir St, <br> Cambridge, CB1 2LJ, United Kingdom</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="m-contact" id="contact">
  <div class="row">
    <div class="grid-sm-14 grid-lg-12 offset-lg-1">
      <h1>Get in touch.</h1>
      <form action="/contact" method="post" autocomplete="off" id="contactForm">
        <p>Dear vizzuality,</p>
        <div class="form-row">
          <textarea name="message" placeholder="Message" required></textarea>
          <div class="form-row m-contact-email">
            <p id="closeString">Cheers,</p>
            <input name="email" type="email" placeholder="Contact email" required>
          </div>
          <div class="form-row m-contact-submit">
            <button type="submit" class="btn">Send</button>
          </div>
          <input type="hidden" name="_csrf" value="#{csrfToken}">
        </div>
      </form>
      <p class="m-contact-footer">
        Or contact us by email
        <%= link_to 'aGVsbG9Adml6enVhbGl0eS5jb20=', 'mailto:aGVsbG9Adml6enVhbGl0eS5jb20=' %>
      </p>
    </div>
  </div>
</section>

app/views/about/show.html.erb
<% title @team_member.name %>
<% body_class 'is-team-page' %>

<div class="row">
  <div class="grid-sm-14 grid-lg-12 offset-lg-1">
    <article class="m-team">
      <header>
        <div class="photo" style="background-image: url(<%= @team_member.photo.url(:medium) %>)">
          <%= image_tag @team_member.photo.url(:medium) %>
        </div>
        <p class="main-phrase"><%= @team_member.quote %></p>
        <h1><%= @team_member.name %></h1>
        <p class="position"><%= @team_member.position %></p>
      </header>
      <div class="content">
        <%= markdown @team_member.body %>
      </div>
      <footer>
        <p>
          <% if @team_member.twitter_user %>
            <%= link_to 'Twitter', "https://twitter.com/#{@team_member.twitter_user}" %><br>
          <% elsif @team_member.dribble_user %>
            <%= link_to 'Dribbble', "https://dribbble.com/#{@team_member.dribble_user}" %><br>
          <% elsif @team_member.github_user %>
            <%= link_to 'Github', "https://github.com/#{@team_member.github_user}" %><br>
          <% elsif @team_member.behance_user %>
            <%= link_to 'Behance', "https://www.behance.net/#{@team_member.behance_user}" %><br>
          <% elsif @team_member.linkedin_user %>
            <%= link_to 'Linkedin', "#{@team_member.linkedin_user}" %><br>
          <% end %>
          <%= link_to 'Email', "mailto:#{@team_member.email}" %>
        </p>
      </footer>
    </article>
  </div>
</div>

<%= render 'about/hiring' %>
<%= render 'about/pagination' %>